[toolchain]
anchor_version = "0.32.1"
rust_version = "1.75.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_token = "testToken111111111111111111111111111111111"

[programs.devnet]
test_token = "testToken111111111111111111111111111111111"

[programs.testnet]
test_token = "testToken111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator.clone]
url = "https://api.devnet.solana.com"

[test.validator.clone.upgrade_authority]
address = ""

[test.validator.account]
[test.validator.account."spl-token"]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
executable = true
filename = "spl_token-3.5.0.so"

[test.validator.account."spl-token-2022"]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
executable = true
filename = "spl_token_2022-1.1.1.so"

[test.validator.account."spl-associated-token-account"]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
executable = true
filename = "spl_associated_token_account-1.1.2.so"

[test.validator.account."spl-memo"]
address = "MemoSq4gqABAXKb96qnH8TysNcWxCyWCfbXFu4E3Hw"
executable = true
filename = "spl_memo-1.0.0.so"

[test.validator.account."spl-memo-3"]
address = "Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo"
executable = true
filename = "spl_memo-3.0.0.so"

